name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with: 
        files: src/PlayFabBuddy.Cli/settings.json
      env:
        titleId: ${{ secrets.PFTITLEID }}
        devSecret: ${{ secrets.PFDEVSECRET }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger GitHubActions
      
    - name: "TODO to Issue"
      uses: "alstr/todo-to-issue-action@v4"
      id: "todo"
      with:
        CLOSE_ISSUES: false
        AUTO_ASSIGN: true
